<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.github.thunkware</groupId>
    <artifactId>auto-valhalla</artifactId>
    <version>0.1.1-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>auto-valhalla-tests</artifactId>
  <packaging>pom</packaging>
  <name>auto-valhalla-tests</name>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
        <configuration>
          <skipSource>true</skipSource>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <configuration>
          <skip>true</skip>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <modules>
    <module>test-jdk5</module>
    <module>test-jdk17</module>
    <!--<module>test-maven-plugin-jdk8</module> don't add to module list -->
    <module>test-maven-plugin-jdk28</module>
    <module>test-maven-plugin-no-compiler</module>
    <module>test-maven-plugin-nested-compiler</module>
    <module>test-maven-plugin-parent-config</module>
    <module>test-maven-plugin-remove-annotation</module>
  </modules>
</project>
