package io.github.thunkware.auto.valhalla.maven;

import static io.github.thunkware.auto.valhalla.maven.Utils.plural;

import io.github.thunkware.auto.valhalla.processor.AutoValhallaProcessor;
import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.inject.Inject;
import org.apache.maven.artifact.DependencyResolutionRequiredException;
import org.apache.maven.execution.MavenSession;
import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.BuildPluginManager;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.plugins.annotations.ResolutionScope;
import org.apache.maven.project.MavenProject;

/**
 * Runs only the {@code auto-valhalla} annotation processor: a
 * {@code javac -proc:only} selection pass over the project's source roots that
 * selects the {@code @AutoValhalla}-annotated top-level types and generates
 * generated copies of their source files (with {@code value class}/
 * {@code value record}) under
 * {@code <buildDirectory>/auto-valhalla-generated-sources}.
 *
 * <p>Unlike the {@code transform} goal, nothing is compiled and nothing is
 * written under the project's output directory, so this goal is useful to
 * inspect (or post-process) what would be transformed without producing the
 * multi-release value classes.
 */
@Mojo(name = "process-sources", defaultPhase = LifecyclePhase.PROCESS_SOURCES, threadSafe = true,
        requiresDependencyResolution = ResolutionScope.COMPILE_PLUS_RUNTIME)
public class ProcessSourcesMojo extends AbstractMojo {

    /**
     * Skip the annotation-processor pass entirely.
     */
    @Parameter(defaultValue = "false", property = "auto-valhalla.skip")
    private boolean skip;

    /**
     * Maven's {@code target} directory, used for the generated sources.
     */
    @Parameter(defaultValue = "${project.build.directory}", readonly = true, required = true)
    private File buildDirectory;

    @Parameter(defaultValue = "${project.build.outputDirectory}", readonly = true, required = true)
    private File outputDirectory;

    /**
     * Fail the build when an annotated class cannot be generated by the
     * processor. Mirrors the agent's {@code annotation.rejected}/
     * {@code annotation.fail} defaulting to {@code fatal}.
     */
    @Parameter(defaultValue = "true")
    private boolean failOnAnnotationFailure;

    /**
     * Override for the JDK compiler executable. When Maven runs on JDK 8
     * through 27, {@code JAVA28_HOME} must point to the JDK 28 compiler; on
     * JDK 28, the running JDK compiler is used by default.
     */
    @Parameter(property = "auto-valhalla.javac")
    private String javac;

    /**
     * Character encoding for the selection pass. Defaults to
     * {@code ${project.build.sourceEncoding}} or UTF-8.
     */
    @Parameter(property = "auto-valhalla.encoding", defaultValue = "${project.build.sourceEncoding}")
    private String encoding;

    @Parameter(defaultValue = "${project}", readonly = true, required = true)
    private MavenProject project;

    /**
     * The current Maven session, so the jar-plugin version check runs at
     * most once per Maven run across all modules and goals.
     */
    @Parameter(defaultValue = "${session}", readonly = true, required = true)
    private MavenSession session;

    @Inject
    private BuildPluginManager pluginManager;

    @Override
    public void execute() throws MojoExecutionException, MojoFailureException {
        if (skip) {
            getLog().info("auto-valhalla: skipping source processing");
            return;
        }
        JarPluginCheck.checkOnce(session, project, getLog());
        JdkVersion.validate();
        List<String> compileClasspath;
        try {
            compileClasspath = project.getCompileClasspathElements();
        } catch (DependencyResolutionRequiredException e) {
            throw new MojoExecutionException("auto-valhalla: could not resolve the project's "
                    + "compile classpath for javac: " + e.getMessage(), e);
        }
        String processorPath = AutoValhallaProcessor.processorPath();
        if (processorPath == null) {
            throw new MojoExecutionException("auto-valhalla: could not locate the "
                    + "auto-valhalla-processor jar for javac's -processorpath");
        }
        Selection selection;
        try {
            Input input = Input.builder()
                    .sourceRoots(project.getCompileSourceRoots())
                    .buildDirectory(buildDirectory)
                    .outputDirectory(outputDirectory)
                    .javac(javacExecutable())
                    .processorPath(processorPath)
                    .compileClasspath(compileClasspath)
                    .encoding(resolveEncoding())
                    .session(session)
                    .project(project)
                    .pluginManager(pluginManager)
                    .build();
            AnnotationProcessorRunner runner = new AnnotationProcessorRunner(getLog());
            selection = runner.run(input);
        } catch (IOException e) {
            throw new MojoExecutionException("auto-valhalla: failed during the "
                    + "annotation-processor pass: " + e.getMessage(), e);
        }

        if (selection.selectedTypes().isEmpty()) {
            getLog().info("auto-valhalla: no @AutoValhalla-annotated classes found");
        } else {
            int count = selection.selectedTypes().size();
            getLog().info("auto-valhalla: processed " + count
                    + " @AutoValhalla-annotated class" + plural(count) + "; generated sources under "
                    + selection.generatedSources().getAbsolutePath());
        }
    }

    private String resolveEncoding() {
        return Utils.normalizeEncoding(encoding);
    }

    private String javacExecutable() {
        return Javac.resolveExecutable(javac, TransformMojo.MIN_VALHALLA_JDK);
    }
}
